name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - name: Build Deb
        uses: L1ghtmann/theos-build@main
        with:
          extra_args: "XCODE=/Applications/Xcode_14.0.1.app FINALPACKAGE=1"

      - uses: actions/upload-artifact@main
        with:
          name: package
          path: packages/*.deb

  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@main
      - name: Download Artifact
        uses: actions/download-artifact@main

      - name: Set TAG Variable
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: $TAG
          release_name: $TAG
          body: ''
          draft: true

      - name: Attach Deb To Release
        run: |
          set -x
          debs=()
          for deb in **/*.deb; do
            debs+=("-a" "$deb")
          done
          hub release edit "${debs[@]}" -m "$TAG" "$TAG"
