name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - name: Build package
        uses: L1ghtmann/theos-build@main
        with:
          extra_args: "XCODE=/Applications/Xcode_14.0.1.app FINALPACKAGE=1"

      - uses: actions/upload-artifact@main
        with:
          name: package
          path: packages/*.deb

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 5.7
          release_name: libswift v5.7
          draft: false
          prerelease: false

      - name: Attach package to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          debs=()
          for deb in **/*.deb; do
            debs+=("-a" "$deb")
          done
          hub release edit "${debs[@]}" -m "libswift v5.7" "5.7"
